# Generated by Django 5.1.6 on 2025-05-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firefighters',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.firestation'),
        ),
    ]
