# Generated by Django 5.1.6 on 2025-05-21 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0003_firefighters_badge_number_firefighters_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firestation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fire.locations'),
        ),
    ]
