# Generated by Django 5.1.6 on 2025-05-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0005_firestation_email_firestation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherconditions',
            name='date',
            field=models.DateField(default='2025-05-21'),
        ),
    ]
